### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by joelfourhman** [RedSiege/AutoFunkt#1]
no LICENSE included, which means all rights reserved by FortyNorth.

If this is intended, please make note of it in the README.md or add a LICENSE file describing 'all rights reserved'

**Comment by a-3-r** [comment]
GPLv3 license added in [a5d50aa](https://github.com/FortyNorthSecurity/AutoFunkt/commit/a5d50aa2938a3f7bc24b29988d20d57260705b50)
